/** Versioned notices: stored with checkout acceptance, independent of locale. */
export const LEGAL_VERSION = "2026-10-01";
export const LEGAL_PATHS = ["privacy", "terms", "cancellation", "accessibility"] as const;
export type LegalPage = typeof LEGAL_PATHS[number];

export const serviceCopy = {
  he: {
    navigation: "שירות ומידע", support: "עזרה ויצירת קשר", privacy: "מדיניות פרטיות", terms: "תנאי שימוש", cancellation: "ביטול עסקה והחזרים", accessibility: "נגישות",
    updated: "עודכן ב־1 באוקטובר 2026", business: "פרטי העסק", name: "שם העסק", number: "מספר עוסק / חברה", address: "כתובת", email: "מייל", phone: "טלפון", hours: "שעות מענה",
    pending: "פרטי העסק ודרכי ההתקשרות הנוספים יושלמו לפני פתיחת השירות לציבור. זו סביבת הכנה ובדיקה.",
    photoNotice: "התמונה, השם והגיל משמשים ליצירת הדמות והמשחק, בעזרת ספקי AI, אחסון ואירוח. המסירה מרצון; בלי תמונה ואישור הורה לא ניתן ליצור משחק אישי. פרטי העיבוד, השיתוף וזכויות העיון והתיקון מופיעים במדיניות הפרטיות.",
    acceptance: "אני בגיל 18 ומעלה, קראתי ואני מסכים/ה לתנאי השימוש ולמדיניות הביטול.", acceptanceRequired: "יש לאשר את תנאי השימוש ומדיניות הביטול לפני התשלום.",
    checkoutNotice: "רכישה חד־פעמית של העולמות שבחרתם, ללא מנוי. יצירת המשחק מתחילה לאחר אישור התשלום. החזר מלא ניתן בבקשה בתוך 14 יום מהרכישה או ממסירת המשחק, לפי המאוחר. זכויותיכם לפי החוק נשמרות.",
    supportLead: "עזרה במשחק, שאלה על רכישה, בקשת ביטול או פנייה בנושא פרטיות ונגישות — הכול במקום אחד.",
    requestTitle: "שליחת פנייה", topic: "נושא", topics: { help: "עזרה במשחק או בהזמנה", cancellation: "הודעת ביטול עסקה ובקשת החזר", privacy: "עיון, תיקון או מחיקת מידע", accessibility: "קושי בנגישות" },
    contactEmail: "המייל לחזרה אליכם", order: "מספר הזמנה או משחק (אם יש)", message: "מה תרצו שנדע? (לא חובה)",
    minimisation: "אין לצרף תמונת ילד, סיסמה, פרטי אשראי או תעודת זהות. לבקשת ביטול מספיקים המייל שבו בוצעה הרכישה ופרט שיאפשר לנו לאתר אותה; אפשר לשלוח גם בלי מספר הזמנה.",
    requestPrivacy: "פרטי הפנייה נשמרים לצורך טיפול, אימות ומתן מענה, ונגישים לצוות מורשה בלבד. אפשר לבקש עיון ותיקון. בלי כתובת מייל לא נוכל לחזור אליכם.",
    submit: "שליחת הפנייה", submitting: "שולחים…", failure: "הפנייה לא נשמרה. אפשר לנסות שוב או לפנות במייל או בטלפון שמופיעים בעמוד. אין אישור קבלה עד שמוצג מספר פנייה.",
    receipt: "הפנייה התקבלה ונשמרה", receiptId: "מספר פנייה", receivedAt: "התקבלה בתאריך", receiptNote: "שמרו את מספר הפנייה או הדפיסו אישור זה. אין צורך לשלוח שוב. הודעת ביטול נרשמת במועד הקבלה המוצג כאן; ביצוע הזיכוי ואישור הטיפול יימסרו בנפרד. אין צורך להתחבר לחשבון כדי לפנות.",
    print: "הדפסת אישור", another: "פנייה נוספת", required: "יש להזין כתובת מייל תקינה.", fallback: "אפשר לפנות גם במייל, בטלפון או בדואר באמצעות פרטי העסק. משלוח דואר אינו תנאי לביטול.",
  },
  en: {
    navigation: "Help & information", support: "Help & contact", privacy: "Privacy policy", terms: "Terms of use", cancellation: "Cancellations & refunds", accessibility: "Accessibility",
    updated: "Updated October 1, 2026", business: "Business details", name: "Business name", number: "Business registration number", address: "Address", email: "Email", phone: "Phone", hours: "Support hours",
    pending: "The remaining business and contact details will be completed before public launch. This is a preparation and testing environment.",
    photoNotice: "The photo, name and age are used to create the character and game with AI, storage and hosting providers. Providing them is voluntary; a personalised game requires a photo and parental permission. Our privacy policy explains processing, sharing, access and correction rights.",
    acceptance: "I am 18 or older, have read and agree to the terms of use and cancellation policy.", acceptanceRequired: "Please accept the terms of use and cancellation policy before payment.",
    checkoutNotice: "A one-time purchase of your selected worlds, without a subscription. Creation begins after payment confirmation. Request a full refund within 14 days of purchase or game delivery, whichever is later. Your statutory rights remain unaffected.",
    supportLead: "Help with a game, a purchase question, a cancellation notice, or a privacy or accessibility request — all in one place.",
    requestTitle: "Send a request", topic: "Topic", topics: { help: "Game or order help", cancellation: "Cancellation notice and refund request", privacy: "Access, correct or delete personal data", accessibility: "Accessibility difficulty" },
    contactEmail: "Email for our reply", order: "Order or game number (if available)", message: "Anything you would like us to know? (optional)",
    minimisation: "Do not include a child's photo, password, payment card details or ID document. For cancellation, use the purchase email and any detail that helps us locate the purchase; an order number is not required.",
    requestPrivacy: "Request details are stored to handle, verify and respond to your enquiry, with access limited to authorised staff. You may request access and correction. We need an email address to reply.",
    submit: "Send request", submitting: "Sending…", failure: "Your request was not saved. Try again or use the email or phone listed on this page. Receipt is confirmed only when a reference number appears.",
    receipt: "Your request was received and saved", receiptId: "Reference number", receivedAt: "Received on", receiptNote: "Save your reference number or print this receipt. You do not need to resend it. A cancellation notice is recorded at the time shown here; refund processing and the resolution will be confirmed separately. Signing in is not required to contact us.",
    print: "Print receipt", another: "Another request", required: "Enter a valid email address.", fallback: "You can also contact us by email, phone or post using the business details. Sending a letter is not a condition of cancellation.",
  },
};

export const legalDocuments: Record<"he" | "en", Record<LegalPage, { lead: string; sections: { title: string; paragraphs: string[] }[] }>> = {
  he: {
    privacy: {
      lead: "משחק אישי דורש מידע אישי. כאן מוסבר מה אנחנו מקבלים, למה הוא משמש, מי מעבד אותו ואיך אפשר לשלוט בו.",
      sections: [
        { title: "מי אחראי למידע", paragraphs: ["העסק שפרטיו מופיעים בהמשך מפעיל את FindMe Worlds (איפה אני?) ואחראי למידע שנאסף במסגרת השירות. פרטי העסק ודרכי הפנייה מופיעים בהמשך ובעמוד העזרה."] },
        { title: "מה נאסף ולמה", paragraphs: ["ביצירת משחק מתקבלים שם הילד או כינוי, גיל ותמונה שאתם בוחרים להעלות. אלה משמשים ליצירת דמות מאוירת, התאמת מבנה הגוף לגיל, יצירת מחבואים ובדיקת איכות. אין צורך למסור שם משפחה, בית ספר, מיקום או מסמך מזהה של הילד.", "כתובת המייל של המבוגר משמשת לניהול החשבון, מסירת קישורי כניסה ומשחק, טיפול בהזמנה ובפניות שירות. נשמרים גם פרטי ההזמנה וסטטוס התשלום, התקדמות במשחק, גילויים בדרכון, העדפות שפה ונתוני תפעול ואבטחה כגון זמני פעילות, שגיאות וכתובת IP בבקשות לשרת.", "מסירת המידע היא מרצון ואינה חובה חוקית. בלי תמונה, פרטי ילד ואישור הורה לא נוכל ליצור משחק אישי; בלי מייל לא נוכל לנהל רכישה או להשיב לפנייה. אפשר לנסות את ההדגמה ללא העלאת תמונה."] },
        { title: "ילדים והסכמת הורה", paragraphs: ["הרכישה והעלאת התמונה מיועדות למבוגר בן 18 ומעלה, שהוא הורה, אפוטרופוס מוסמך או מי שפועל באישורם המפורש. יש להעלות תמונה רק כשיש הרשאה לכך, ולהימנע מתמונות של ילדים אחרים. רכישת מתנה אינה מחליפה את הסכמת ההורה לתמונה. הילדים יכולים לשחק במשחק שהוכן עבורם בהשגחת המבוגר."] },
        { title: "AI וספקי שירות", paragraphs: ["תמונות, חיתוכים מהן, דמות מאוירת וגיל או הנחיות התאמה עשויים להישלח ל־OpenAI לצורך יצירה ובדיקת איכות באמצעות ה־API. זו התאמה אמנותית ולא שירות לזיהוי אדם או לאימות זהותו. דמות שנוצרה ב־AI אינה העתק מדויק של צילום.", "Vercel מספקת אירוח; ספקי מסד נתונים ואחסון משמשים לשמירת המשחק והמידע; Resend משמשת למיילים תפעוליים; ספק הסליקה שמוצג בעת התשלום מעבד את פרטי התשלום. אין להזין פרטי אשראי בטופסי האתר או התמיכה. ספקים עשויים לעבד מידע מחוץ לישראל, לפי ההתקשרויות ומדיניות העיבוד שלהם.", "המידע משמש לתפעול השירות ואינו מוצע למכירה או לפרסום תמונות ילדים. אין בקוד השירות מסלול לאימון מודל על תמונות שהועלו. שמירת מידע אצל ספק AI אינה בהכרח זהה לשמירה אצלנו; מדיניות הספק והגדרות החשבון חלות גם עליה. לא מובטחת מחיקה מיידית או אפס שמירה אצל ספקים."] },
        { title: "קישורים ושיתוף", paragraphs: ["המשחק אינו מפורסם בגלריה ציבורית מטעם השירות. עם זאת, מי שמחזיק בקישור המשחק יכול לפתוח אותו ולראות את הדמות והתוכן שלו. אין להעביר קישור כניסה אישי לחשבון. שיתוף דרכון מופעל בנפרד, וניתן לבטל או להחליף את הקישור באזור המשפחתי.", "ביטול קישור חוסם גישה חדשה באמצעותו. הוא אינו מוחק צילום מסך, הורדה או עותק שכבר נשמרו אצל מקבל הקישור."] },
        { title: "הזמנות למשחק עם חברים", paragraphs: ["הורה יכול להפעיל הזמנה נפרדת לעולם אחד ממשחק מסוים. מקבלי הקישור יכולים לראות את העולם, הדמות המאוירת ושם הילד או הכינוי שמוצג במשחק, בלי גישה לאזור המשפחתי, לתמונה המקורית או לתמונות הזהות הפרטיות. ההזמנה תקפה ל־30 יום ואפשר לסגור או להחליף אותה. היא אינה קישור לשיתוף הדרכון.", "האורחים בוחרים כינוי מתוך רשימה, ללא מסירת שם אמיתי, מייל או תמונה וללא פתיחת חשבון. נשמרים מזהה משתתף, הכינוי, התקדמות נפרדת, מקומות שביקרו בהם, מחבואים ותגליות שמצאו, שימוש ברמזים, זמני פעילות ותגובה מוכנה מראש שבחרו לשלוח. בעל החשבון יכול לראות את התוצאות והתגובה ולהסיר משתתף; אורחים אינם מקבלים גישה לתוצאות של אחרים. המשחק של האורחים אינו משנה את ההתקדמות של בעל המשחק.", "תוצאות האורחים מיועדות למחיקה במחזור תחזוקה כעבור 90 יום מתפוגת ההזמנה או מסגירתה, לפי המוקדם. מחיקת המשחק מוחקת גם את ההזמנות והתוצאות שלו. סגירת הזמנה מונעת גישה חדשה; תוכן שכבר נטען לדפדפן או נשמר אצל מקבל הקישור אינו נמחק מרחוק."] },
        { title: "שמירה ומחיקה", paragraphs: ["המשחק, הדמות והדרכון נשמרים כדי לאפשר משחק והמשך מסע. התמונה המקורית עשויה להישאר לצורך יצירה ותיקונים עד להשלמת התהליך; מועדי מחיקתה תלויים גם במסלול היצירה. אפשר לבקש מחיקה דרך עמוד העזרה או למחוק משחק דרך ניהול המשחק. מחיקת משחק מפסיקה את הגישה אליו ומפעילה מחיקת הנכסים האישיים שלו.", "מנגנון הניקוי מטפל בתמונות של טיוטות שלא שולמו ולא היו פעילות במשך 7 ימים, בתמונה שלא הוחלפה לאחר בקשה לתמונה חדשה במשך 30 יום, ובניסיונות איור שנדחו לאחר 14 יום. הניקוי מתבצע במחזורי תחזוקה, ולא בהכרח בשנייה שבה מסתיים פרק הזמן.", "פרטי פניות שירות נשמרים עד 12 חודשים ממועד קבלתן ואז נמחק התוכן האישי שלהן במחזור תחזוקה. יומני תפעול, מסמכי עסקה ומידע שיש לשמור מכוח הדין או לצורך בירור מחלוקת עשויים להישמר בנפרד ככל שנדרש. עותקי גיבוי ונתונים אצל ספקים כפופים למחזורי השמירה שלהם; מחיקה מהשירות אינה הבטחה למחיקה מיידית מכל גיבוי."] },
        { title: "עוגיות ואחסון בדפדפן", paragraphs: ["משתמשים בעוגיות ובאחסון בדפדפן לצורך כניסה, שמירת טיוטה, בחירת שפה, גישה ל־QA ושמירת התקדמות מקומית. בהזמנות לחברים הם משמשים גם לזיהוי המשתתף בדפדפן ולשמירת התקדמות שטרם סונכרנה. חסימתם עלולה לפגוע בכניסה, ביצירה ובשמירה. בגרסה זו אין שילוב פעיל של מעקב פרסומי או PostHog בדפדפן. אם יתווסף שימוש אחר, המדיניות והבחירות הנדרשות יעודכנו."] },
        { title: "זכויות ופנייה", paragraphs: ["אפשר לבקש לעיין במידע אישי המוחזק עליכם, ולבקש תיקון מידע שאינו נכון, שלם, ברור או מעודכן, בהתאם לדין. ניתן לפנות גם לבקשת מחיקה או הפסקת שימוש. ייתכן שנבקש אימות סביר של בעל החשבון או סמכות ההורה לפני מסירת מידע או מחיקתו; אין לשלוח מסמך מזהה מראש.", "הגישה למידע מוגבלת לפי תפקיד, ונעשה שימוש בבקרות גישה וקישורים מוגנים. אין מערכת שחסינה לחלוטין מפני תקלות או גישה בלתי מורשית. במקרה של חשש לחשיפה, פנו בנושא פרטיות בעמוד העזרה. שינוי מהותי בשימוש במידע ילווה ביידוע מתאים, ובהסכמה כאשר היא נדרשת."] },
      ],
    },
    terms: {
      lead: "התנאים מסבירים מה קונים, איך משתמשים במשחק ומה עושים כשמשהו לא עובד.",
      sections: [
        { title: "המוצר וההתקשרות", paragraphs: ["FindMe Worlds הוא משחק חיפוש דיגיטלי אישי בדפדפן, המופעל בידי העסק שפרטיו מופיעים בהמשך. הרוכש הוא מבוגר בן 18 ומעלה. אלה תנאי השירות; מדיניות הפרטיות ומדיניות הביטול זמינות בנפרד. הדין המחייב וזכויות הצרכן גוברים על הוראה סותרת בתנאים."] },
        { title: "מה כלול ברכישה", paragraphs: ["הרכישה היא חד־פעמית עבור העולמות שבחרתם ושמוצגים בסיכום ההזמנה, עם התאמת דמות לילד ודרכון שמתמלא במהלך המשחק. אין מנוי או חיוב חוזר מכוח רכישה זו. אין התחייבות לקבלת עולמות עתידיים או לכל הקטלוג.", "המחיר הסופי, המטבע, מספר העולמות ומה שכלול מוצגים לפני התשלום. מחיר המשך מיוחס לדרכון של אותו ילד ונבדק לפי רכישותיו; התאמה לילד נוסף היא רכישה נפרדת. התשלום מתבצע אצל ספק הסליקה המוצג, ויצירה מתחילה לאחר אישורו."] },
        { title: "יצירה, מסירה ואיכות", paragraphs: ["הדמות והמחבואים נוצרים ונבדקים באמצעות AI. נדרשת תמונה מתאימה, וייתכן שנבקש תמונה חלופית. הדמיון הוא מאויר ואמנותי; אין הבטחה להעתק פוטוגרפי מדויק. אין בכך פטור מטיפול בפגם או באי־התאמה למה שהוזמן.", "משך ההכנה משתנה לפי מספר העולמות, עומס ותיקונים. מצב ההכנה מופיע באתר. המשחק נמסר באמצעות קישור ומופיע באזור המשפחתי; יש לבדוק גם את תיקיית הספאם. אם היצירה תקועה, משחק לא נמסר או התוצאה בעייתית, פנו לעזרה או לביטול. לא נדרשת הסכמה לקבל משחק פגום.", "דרושים דפדפן עדכני וחיבור לאינטרנט. המשחק מבוסס על חיפוש חזותי, ולכן חלק מהפעולות דורשות ראייה או סיוע ממלווה. השירות אינו מבטיח זמינות רציפה או אחסון ללא הגבלת זמן. במקרה של שינוי מהותי בשירות או הפסקתו יימסר מידע מתאים, וזכויות לגבי רכישה שלא סופקה נשמרות."] },
        { title: "התמונה וההרשאה שלכם", paragraphs: ["יש להעלות רק תמונה שיש לכם זכות ורשות להשתמש בה, באישור ההורה או האפוטרופוס, ולמסור גיל נכון לצורך התאמת הדמות. אין להעלות תמונות פוגעניות או תמונות של אדם אחר ללא הרשאה. אתם נותנים הרשאה מוגבלת לעבד את התמונה באמצעות ספקי השירות לצורך יצירה, בדיקות, תיקונים ומסירת המשחק, כמפורט במדיניות הפרטיות. זו אינה הרשאה לפרסום שיווקי של תמונת הילד."] },
        { title: "שימוש ושיתוף", paragraphs: ["מותר לשחק לשימוש אישי ומשפחתי ולשתף את קישור המשחק עם בני משפחה, חברים או מקבלי המתנה. מי שמחזיק בקישור יכול לפתוח את המשחק. אין לשתף קישור כניסה אישי לחשבון. אפשר לשנות קישורים דרך ניהול המשחק; עותקים שכבר נשמרו אצל אחרים אינם ניתנים להשבה אוטומטית.", "הזמנה נפרדת לחברים מאפשרת לשחק בעולם אחד עם התקדמות עצמאית, בלי לשנות את התקדמות בעל המשחק. ההורה מפעיל ומנהל אותה באזור המשפחתי. פרטי המידע שנשמר, התוצאות שיכול בעל החשבון לראות ותוקף ההזמנה מפורטים במדיניות הפרטיות.", "התוכן, האיורים, הממשק והמותג מוגנים ככל שחלים עליהם דיני קניין רוחני. הרכישה אינה מעבירה בעלות בקטלוג או בתוכנה. אין למכור מחדש את המשחק, להציגו כשירות מסחרי שלכם, לעקוף בקרות גישה או לגשת לתוכן של אחרים. אין בתנאים אלה העברה של זכויותיכם בתמונה המקורית לעסק."] },
        { title: "שירות, ביטול ואחריות", paragraphs: ["אפשר לפנות דרך עמוד העזרה, במייל, בטלפון או בדואר לפי פרטי העסק. מדיניות הביטול מפרטת את ההחזר המלא בתוך 14 יום ואת אופן הגשת ההודעה. בקשה לתיקון אינה תנאי לקבלת ההחזר במסגרת המדיניות.", "נטפל בתקלות סבירות שבאחריות השירות. אין פטור גורף מאחריות ואין ויתור על זכויות שאינן ניתנות לוויתור בדין. הדין הישראלי חל, בלי לגרוע מהוראות מחייבות אחרות החלות על צרכן או מכללי סמכות השיפוט שבדין. עדכון תנאים אינו מצמצם בדיעבד זכויות לגבי רכישה שכבר בוצעה."] },
      ],
    },
    cancellation: {
      lead: "אפשר להתחיל בנחת: החזר מלא בתוך 14 יום מהרכישה או ממסירת המשחק, לפי המאוחר.",
      sections: [
        { title: "המדיניות שלנו", paragraphs: ["אפשר למסור הודעת ביטול ולבקש החזר מלא בתוך 14 יום ממועד הרכישה או ממסירת המשחק, לפי המאוחר. המדיניות חלה גם על משחק אישי שכבר נוצר ונמסר. במסגרת מדיניות זו לא נגבים דמי ביטול, ואין חובה לנמק או למצות ניסיונות תיקון.", "אם יש בעיית איכות, אפשר לבחור לבקש תיקון; זו אפשרות ולא תנאי להחזר. אם המשחק לא סופק, יש פגם, אי־התאמה או הפרה אחרת, הזכויות והסעדים לפי הדין נשמרים גם מעבר למדיניות המסחרית הזו. התאמה אישית אינה סיבה לשלילת זכויות גורפת."] },
        { title: "איך מודיעים על ביטול", paragraphs: ["בחרו בעמוד זה או בעמוד העזרה את הנושא ‘הודעת ביטול עסקה ובקשת החזר’. אפשר לפנות גם במייל, בטלפון או בדואר לפי פרטי העסק. אין חובה להתחבר לחשבון, להדפיס טופס או לשלוח דואר רשום כדי להשתמש בטופס המקוון.", "מסרו את המייל שבו בוצעה הרכישה ופרט שמאפשר לאתר אותה. מספר הזמנה או משחק עוזר, אך אינו תנאי לשליחת הודעה. אין צורך לשלוח תמונת ילד, פרטי אשראי או תעודת זהות. אם נדרש אימות, נבקש רק את מה שנחוץ לטיפול.", "לאחר שליחה תקינה בטופס מוצגים מספר פנייה ומועד קבלה שניתן להדפיס או לשמור. הודעת הביטול נרשמת במועד זה; אין צורך לשלוח שוב כדי לשמור את המועד. אם לא מוצג אישור, אין להניח שהטופס התקבל — נסו שוב או השתמשו בדרך פנייה אחרת."] },
        { title: "החזר ומה קורה למשחק", paragraphs: ["לאחר איתור הרכישה ואימותה נמסור אישור טיפול. החזר מלא במסגרת המדיניות יבוצע בתוך 14 יום מקבלת הודעת הביטול, לאמצעי התשלום המקורי ככל שהדבר אפשרי. מועד הופעת הזיכוי בפירוט האשראי תלוי גם בספק התשלום. החזר כספי אינו מתבצע מעצם לחיצה על ‘שליחה’.", "הביטול חל על הרכישה שבוטלה ועל הגישה למשחק שלה. רכישות אחרות של אותו ילד אינן מבוטלות אוטומטית. כשמדובר בחלק מרכישה של כמה עולמות, ציינו מה ביקשתם לבטל ונבהיר את היקף ההחזר לפני הטיפול. בקשת מחיקת מידע מטופלת בנפרד לפי מדיניות הפרטיות."] },
        { title: "זכויות לפי החוק", paragraphs: ["המדיניות המסחרית מוסיפה על זכויותיכם ואינה מחליפה אותן. הוראות הדין לגבי ביטול, פגם, אי־אספקה ומועדים מיוחדים גוברות כאשר הן מעניקות לכם זכות רחבה יותר. לא נדרש ויתור על זכויות כתנאי להגשת פנייה או לקבלת שירות."] },
      ],
    },
    accessibility: {
      lead: "אנחנו רוצים לאפשר למבוגרים ולילדים להשתמש בשירות בנוחות. כאן מפורטים האמצעים הקיימים, המגבלות ודרך הפנייה.",
      sections: [
        { title: "אמצעי נגישות קיימים", paragraphs: ["הממשק כולל כותרות ומבנה עמודים, תוויות לטפסים, סימון מיקוד למקלדת, התאמה לעברית ולאנגלית ולמסכים קטנים. הגדלת הדפדפן אינה חסומה. חיתוך התמונה מאפשר שימוש במקשי החצים ובמקשי פלוס ומינוס, ויש תמיכה בהעדפה לתנועה מופחתת בחלקי הממשק."] },
        { title: "מגבלות ידועות", paragraphs: ["ליבת המשחק היא חיפוש דמות בתוך תמונה עשירה, ואינה מציעה כיום חלופה מלאה ולא־חזותית לפתרון החיפוש. חלק מהשלבים עשויים לדרוש עזרת מלווה. רכיבי תשלום וספקים חיצוניים כפופים גם לממשקים שלהם. לא בוצעה כאן הצהרה על הסמכה או על עמידה מלאה בתקן נגישות."] },
        { title: "עזרה ודיווח", paragraphs: ["אם נתקלתם בקושי, בחרו ‘קושי בנגישות’ בעמוד העזרה או פנו במייל או בטלפון לפי פרטי העסק. כדאי לציין את כתובת העמוד, הפעולה שניסיתם לבצע, הדפדפן והטכנולוגיה המסייעת אם רלוונטי. אין צורך למסור פרטים רפואיים. נבחן את הבעיה ואת האפשרות לסייע או לספק דרך חלופית."] },
      ],
    },
  },
  en: {
    privacy: {
      lead: "A personalised game needs personal information. Here is what we collect, why, who processes it and how you can control it.",
      sections: [
        { title: "Who is responsible", paragraphs: ["The business listed below operates FindMe Worlds (Where Am I?) and is responsible for information collected through the service. Business and contact details are listed below and on the help page."] },
        { title: "Information and purposes", paragraphs: ["We collect the child's first name or nickname, age and a photo you choose to upload to create an illustrated character, adjust body proportions to age, generate hiding spots and check quality. A child's surname, school, location or ID document is not needed.", "The adult's email is used for account access, game delivery, purchases and support. We also store order and payment status, play progress, passport discoveries, language preferences and operational or security data such as activity times, errors and the IP address in server requests.", "Providing information is voluntary, not a legal requirement. A personalised game needs child details, a photo and parental permission; account management and support replies need an email. You can try the demo without uploading a photo."] },
        { title: "Children and parental permission", paragraphs: ["Purchases and photo uploads are for adults aged 18 or older who are a parent, authorised guardian or acting with their express permission. Upload only an authorised photo and avoid photos of other children. Buying a gift does not replace parental permission for a photo. Children can play their prepared game with adult supervision."] },
        { title: "AI and service providers", paragraphs: ["Photos, crops, illustrated characters and age or adaptation instructions may be sent to OpenAI through its API for generation and quality checks. This is artistic personalisation, not identity verification. AI illustrations are not exact photographic copies.", "Vercel provides hosting; database and storage providers hold game data; Resend handles transactional email; the payment provider shown at checkout handles payment details. Never enter card details in our site or support forms. Providers may process data outside Israel under their agreements and processing policies.", "We use information to operate the service, not to sell it or publicly advertise children's photos. The service code contains no workflow for training a model on uploaded photos. Provider retention may differ from ours, and provider policies and account settings also apply. We do not promise immediate deletion or zero retention at providers."] },
        { title: "Links and sharing", paragraphs: ["We do not place personal games in a public gallery. Anyone holding a game link can nevertheless open it and see its character and content. Do not share personal sign-in links. Passport sharing is enabled separately and its link can be revoked or rotated in the family area.", "Revoking a link stops new access through it. It cannot remove screenshots, downloads or copies already saved by recipients."] },
        { title: "Invitations for friends to play", paragraphs: ["A parent can enable a separate invitation for one world from one game. Link recipients can see the world, illustrated character and child's name or nickname shown in the game, without access to the family area, original photo or private identity images. The invitation lasts 30 days and can be closed or replaced. It is separate from passport sharing.", "Guests choose a nickname from a list without providing a real name, email or photo or creating an account. We store a participant identifier, nickname, independent progress, places visited, hiding spots and discoveries found, hint use, activity times and a predefined reaction they choose to send. The account owner can view the results and reaction and remove a participant; guests cannot access other participants' results. Guest play does not change the game owner's progress.", "Guest results are scheduled for deletion in a maintenance cycle 90 days after invitation expiry or closure, whichever comes first. Deleting the game also deletes its invitations and results. Closing an invitation stops new access; content already loaded in a browser or saved by a recipient cannot be remotely removed."] },
        { title: "Retention and deletion", paragraphs: ["Games, characters and passports are retained to support play and continuation. The original photo may remain during generation and repairs; deletion timing also depends on the creation pipeline. Request deletion through help or delete a game in its management page. Game deletion stops access and triggers deletion of its personal assets.", "Maintenance removes photos in unpaid drafts inactive for 7 days, an unreplaced photo 30 days after a request for a new one, and rejected generation attempts after 14 days. Cleanup runs in maintenance cycles rather than at the exact expiry second.", "Support request personal content is retained for up to 12 months from receipt and then removed in a maintenance cycle. Operational records, transaction documents and information needed by law or for a dispute may be retained separately as necessary. Backups and provider records follow their retention cycles; deletion here is not a promise of immediate removal from every backup."] },
        { title: "Cookies and browser storage", paragraphs: ["Cookies and browser storage support sign-in, drafts, language, QA access and local progress. Friend invitations also use them to identify a participant in the browser and retain progress awaiting synchronisation. Blocking them may affect access, creation or saving. This version has no active advertising tracking or browser PostHog integration. Any additional use will require updated notices and choices where applicable."] },
        { title: "Rights and contact", paragraphs: ["You may request access to personal information held about you and correction of information that is inaccurate, incomplete, unclear or outdated, as provided by law. You can also request deletion or cessation of use. We may require reasonable account or parental authority verification before disclosing or deleting information; do not send ID documents in advance.", "Access is restricted by role and protected links. No system is completely immune to failures or unauthorised access. Use the privacy topic on the help page if you suspect exposure. Material changes to data use will be accompanied by appropriate notice and consent where required."] },
      ],
    },
    terms: {
      lead: "What you purchase, how to use the game and what to do if something goes wrong.",
      sections: [
        { title: "The service and agreement", paragraphs: ["FindMe Worlds is a personalised digital search game played in a browser, operated by the business listed below. Purchasers must be 18 or older. Privacy and cancellation policies are separately available. Mandatory law and consumer rights take precedence over conflicting terms."] },
        { title: "Your purchase", paragraphs: ["A one-time purchase includes the worlds selected and shown in your order summary, a personalised child character and a passport filled during play. This purchase creates no subscription or recurring charge. It does not include future worlds or the entire catalogue.", "The final price, currency, number of worlds and included content are shown before payment. Continuation pricing belongs to the same child's passport and is verified against their purchases; another child's personalisation is a separate purchase. Payment is handled by the displayed payment provider, and creation begins after confirmation."] },
        { title: "Creation, delivery and quality", paragraphs: ["AI creates and reviews the character and hiding spots. A suitable photo is required; we may request a replacement. Likeness is artistic and illustrated rather than an exact photographic copy. This does not excuse a defect or a mismatch with the purchase.", "Preparation time varies with world count, demand and repairs. The site shows progress. Delivery is by link and in the family area; also check spam. Contact help or cancellation if creation stalls, the game is not delivered or the result has a problem. You do not have to agree to receive a defective game.", "A current browser and internet connection are required. The game is visual and some tasks require sight or help from a companion. Continuous availability and indefinite storage are not guaranteed. Material service changes or discontinuation will be accompanied by appropriate information, without affecting rights concerning undelivered purchases."] },
        { title: "Your photo and permission", paragraphs: ["Upload only a photo you have the right and parental or guardian permission to use, and provide the correct age. Do not upload harmful content or someone else's photo without permission. You grant limited permission to process the photo with service providers for creation, checks, repairs and delivery as described in the privacy policy, not for marketing a child's photo."] },
        { title: "Use and sharing", paragraphs: ["Play for personal and family use and share game links with family, friends or gift recipients. A link holder can open the game. Do not share account sign-in links. Links can be changed in game management, but saved copies cannot be automatically recalled.", "A separate friend invitation allows independent progress in one world without changing the game owner's progress. A parent enables and manages it in the family area. The privacy policy describes stored information, results visible to the account owner and invitation expiry.", "Content, illustrations, interface and branding are protected where intellectual property laws apply. Purchasing does not transfer ownership of the catalogue or software. Do not resell the game, offer it as your own commercial service, bypass access controls or access other users' content. These terms do not transfer your original photo rights to the business."] },
        { title: "Help, cancellation and responsibility", paragraphs: ["Contact us through help, email, phone or post using the listed business details. The cancellation policy describes full refunds within 14 days and how to give notice. Attempting a repair is not a condition of that refund.", "We address reasonable faults within the service's responsibility. There is no blanket exclusion of liability or waiver of non-waivable rights. Israeli law applies without overriding other mandatory consumer protections or lawful jurisdiction rules. Updated terms do not retroactively reduce rights for an existing purchase."] },
      ],
    },
    cancellation: {
      lead: "Start with confidence: a full refund within 14 days of purchase or game delivery, whichever is later.",
      sections: [
        { title: "Our policy", paragraphs: ["Give a cancellation notice and request a full refund within 14 days of purchase or delivery, whichever is later. This includes personalised games already created and delivered. There is no cancellation fee under this policy, no requirement to give a reason and no requirement to exhaust repair attempts.", "You may choose a repair for a quality issue, but it is not a condition of a refund. Rights and remedies for non-delivery, defects, mismatch or other breach remain available under applicable law beyond this commercial policy. Personalisation is not a blanket reason to deny rights."] },
        { title: "How to cancel", paragraphs: ["Choose ‘Cancellation notice and refund request’ on this page or on help. You may also contact us by email, phone or post using the business details. The online form does not require sign-in, a printed form or a registered letter.", "Provide the purchase email and a detail allowing us to locate it. An order or game number is helpful but not required to send notice. Do not send a child's photo, card details or ID document. If verification is needed, we will ask only for necessary information.", "Successful submission shows a reference number and receipt time you can save or print. The cancellation notice is recorded at that time; resending is unnecessary to preserve it. If no confirmation appears, do not assume receipt: retry or use another contact method."] },
        { title: "Refund and game access", paragraphs: ["After locating and verifying the purchase we will confirm handling. A full refund under this policy is processed within 14 days of the cancellation notice, to the original payment method where possible. The payment provider also affects when the credit appears. Pressing ‘Send’ does not itself execute a refund.", "Cancellation applies to the cancelled purchase and access to its game. Other purchases for the same child are not automatically cancelled. For part of a multi-world purchase, specify what you wish to cancel so we can explain the refund scope before handling it. Data deletion requests are handled separately under the privacy policy."] },
        { title: "Statutory rights", paragraphs: ["This policy adds to your rights, not replaces them. Mandatory cancellation, defect, non-delivery and special-period protections prevail when more favourable. No waiver of rights is required to contact us or obtain service."] },
      ],
    },
    accessibility: {
      lead: "We want adults and children to use the service comfortably. These are the current features, limitations and contact options.",
      sections: [
        { title: "Existing features", paragraphs: ["The interface includes headings and page structure, form labels, keyboard focus indication, Hebrew and English layouts and small-screen adaptation. Browser zoom is not blocked. Photo cropping supports arrow keys and plus/minus, and parts of the interface respect reduced-motion preferences."] },
        { title: "Known limitations", paragraphs: ["The core game searches for a character inside a detailed picture and currently has no complete non-visual alternative to solving the search. Some steps may need a companion's help. External payment and provider interfaces also have their own behaviour. This notice makes no certification or full accessibility-standard compliance claim."] },
        { title: "Help and reporting", paragraphs: ["Choose ‘Accessibility difficulty’ on help or use the listed email or phone. Include the page address, attempted action, browser and assistive technology if relevant. Medical details are not needed. We will assess the issue and options for assistance or an alternative path."] },
      ],
    },
  },
};
