/** Private, no-network source-blind fixed-slot authoring and six-silhouette audit. */
import { readFileSync, existsSync, mkdirSync } from 'node:fs';
import sharp from 'sharp';
import { sha256Bytes } from '../src/services/generation/fixed-sprite';
import { findSimplePeekCut, composeSimplePeek } from '../src/services/generation/simple-peek';
import { chooseRobustPeekCut } from '../src/services/generation/robust-peek-cut';
import { loadBoardConditioningInputs } from './board-conditioned-inputs';
import { prepareBoardConditionedSource } from '../src/services/generation/board-conditioned-source';
import { writeImmutableBytes } from './board-conditioned-probe-replay';

const ROOT = 'work/open-placement-20260909/author-batch-v1';
const OLD = 'work/board-conditioned-engine-20260909';
const CATALOG = 'work/fixed-world-simple-20260908/board-conditioned-engine-v1/visual-directions-v4.json';
const RUNS: Record<string,string[]> = { amazon:['world-amazon-v2/replays/speckle-bound-v1','noa-amazon'], giza:['world-giza-v2/replays/speckle-bound-v1','noa-giza'], greatwall:['world-greatwall','noa-greatwall'], marrakech:['world-marrakech-v3','noa-marrakech-v2'], tokyo:['world-tokyo','noa-tokyo'] };
const read = (p:string) => JSON.parse(readFileSync(p,'utf8'));
const out = (p:string,v:unknown) => writeImmutableBytes(p,JSON.stringify(v,null,2));
type Point = {x:number;y:number};
type Rect = {left:number;top:number;width:number;height:number};
type Candidate = {keep?:string;id?:string;pose?:string;eye?:Point;face?:number;ground?:number;height?:number;person?:Rect;context?:Rect;polygon?:Point[];action?:string;light?:{keyDirection:string;colorTemperature:string;relativeIntensity:string;fillAndBounce:string;shadow:string};reuseMask?:string;forbidden?:Rect[];basis?:string};
const rect = (x:number,y:number,w:number,h:number):Rect => ({left:Math.round(x*1.6),top:Math.round(y*1.6),width:Math.round(w*1.6),height:Math.round(h*1.6)});
const pt = (x:number,y:number):Point => ({x:Math.round(x*1.6),y:Math.round(y*1.6)});
const light = (key:string,temp:string,level:string,fill:string) => ({keyDirection:key,colorTemperature:temp,relativeIntensity:level+'; match neighboring original people; no luminous face, saturated portrait clothes or bright orange hair rim',fillAndBounce:fill,shadow:'Broad painted local shadow planes on face, hands, hair and clothes together. Preserve intrinsic complexion. Restrained highlights, no detached scenery or cast shadow.'});
const config:Record<string,Candidate[]> = {
  amazon:[
    {id:'amazon-root-pocket-compact-v2',reuseMask:'amazon-root-log-left-peek',pose:'side-lean',eye:{x:590,y:1295},face:24,context:{left:330,top:1090,width:512,height:512},person:rect(235,702,100,139),action:'Compact upper body leaning gently RIGHT behind the thick existing root, shoulders and elbows close. Three-quarter face watches a butterfly over the river, one small hand near the chest. No branch, leaf, root, river or other prop generated.',light:light('Soft upper-left canopy opening','Deep olive canopy shade with muted warm accents','Low canopy exposure matching the nearby shaded original child','Restrained olive environmental reflection, never green skin'),basis:'Same broad painted root pocket; source-blind 15 native-pixel lower eye and face 24 versus26 for compact child scale. No mask pixels changed.'},
    {id:'amazon-far-bank-compact-v2',reuseMask:'amazon-upper-bank-rock-front-peek',pose:'crouch',eye:{x:2110,y:590},face:16,context:{left:1950,top:400,width:310,height:270},person:rect(1291,392,77,94),action:'Low compact crouch behind the existing far-bank rock, shoulders lowered, torso slightly forward. Turn face three-quarter LEFT looking at the canoe, both hands held close below chest. Child at the scale of the nearby far-bank children. No rock, canoe or water generated.',light:light('Soft open sky beside misty foliage','Neutral soft daylight with weak green fill','Quiet distant-bank midtones, not a foreground portrait','Low-contrast sky and foliage reflection'),basis:'Same far-bank support/occluder; eye 10 native pixels lower to meet the broad original bank, retaining original measured face scale.'},
    {id:'amazon-open-shaded-porch-v2',pose:'standing',eye:pt(1738,461),ground:550*1.6,height:108*1.6,face:15*1.6,person:rect(1755,418,59,132),action:'Stand on the existing shaded wooden porch, both shoes fully visible on the boards. Turn three-quarter LEFT toward the fruit sellers, arms relaxed with one small hand close to the waist. Natural small child waiting in the group, no fruit, basket, porch or scenery generated.',light:light('Broad daylight filtered by the thatched eave','Warm subdued wood bounce over olive canopy shade','Porch shade matching the neighboring original standing child, no sunlit face','Restrained olive ambient and warm timber reflection'),basis:'Clear wooden porch gap between the original white-shirt and green-shirt children. The adjacent standing child establishes same-depth scale; feet use the porch under the existing eave, not exposed ground.'},
  ],
  greatwall:[
    {id:'greatwall-open-shaded-lower-step-v1',pose:'standing',eye:pt(942,1099),ground:1220*1.6,height:132*1.6,face:18*1.6,person:rect(996,1043,70,195),action:'Stand quietly on the broad shaded lower stone step, feet together and both soles planted, arms relaxed. Turn three-quarter LEFT to watch the children with food on the higher landing. Keep a visible three-quarter face; no lantern, food or pole generated.',light:light('Diffuse open sky screened by the higher stone landing','Cool neutral stone shade with weak warm reflected daylight','Subdued shaded step exposure, not sunlit roof exposure','Weak pale-stone bounce; low-contrast blue-grey ambient'),basis:'Original foreground school-age child to the right provides depth scale; shade is already painted on the step. Estimated 132 display-pixel standing height, below the adjacent taller teenager.'},
    {keep:'greatwall-left-stair-planter-side-peek'},
    {id:'greatwall-food-parapet-compact-v2',reuseMask:'greatwall-original-food-parapet-seated',pose:'seated',eye:{x:1358,y:1692},face:21,context:{left:1170,top:1490,width:320,height:380},person:rect(760,938,84,100),action:'Relaxed seated upper torso behind the existing food parapet. Look three-quarter LEFT at the food-sharing children, one forearm inward in the lap, shoulders lowered and elbows compact. The original stone hides seat and legs; do not paint food, mug, plants or a seat.',light:light('Soft upper-left courtyard daylight','Warm daylight with subdued pale-stone fill','Moderate parapet light like neighboring children, never a studio-lit portrait','Weak tan stone and food-stall bounce'),basis:'Same food parapet; source-blind eye 25 native pixels lower so the compact seated torso is hidden by the broad part of the existing stone. Face scale unchanged.'},
  ],
  giza:[
    {keep:'giza-front-engraved-slab-peek'},
    {id:'giza-upright-block-compact-v2',reuseMask:'giza-upright-carved-block-peek',pose:'crouch',eye:{x:2545,y:1006},face:24,context:{left:2310,top:840,width:680,height:660},person:rect(1631,579,87,109),action:'Compact crouching upper body behind the existing broad carved block. Shoulders low, arms tucked inward, face turns three-quarter RIGHT toward nearby children with a curious expression. Face must remain clear of the stone. No stone, tools or props generated.',light:light('Broad upper-left desert daylight','Warm sandy daylight with soft neutral shadow planes','Subdued stone-pocket exposure; highlights weaker than sunlit limestone','Weak sandy reflected fill'),basis:'Shift 40 native pixels left from the crowded right neighbor face; face24px sits within local child head scale. Existing broad block foreground unchanged.'},
    {id:'giza-textile-counter-compact-v2',reuseMask:'giza-folded-textile-counter-peek',pose:'seated',eye:{x:640,y:1350},face:30,context:{left:390,top:1090,width:640,height:730},person:rect(303,702,88,125),action:'Relaxed seated upper body in the cloth-stall shade behind the folded textile counter. Look three-quarter RIGHT toward the vendor, one hand loosely near the lap, elbows tucked inward. No feet or invented seat: the existing textiles hide them. No cloth, cup or prop generated.',light:light('Soft daylight screened by colorful fabric awning','Warm muted fabric shade with restrained neutral skin highlights','Low-to-medium tent shade matching the original stall child','Subtle rust and violet cloth reflection, no bright orange curls'),basis:'Same existing wide textile stack; compact seated eye lowered45 nativepixels and face30 rather than34, matching the nearby stall child. No foregroundmask widened.'},
  ],
  marrakech:[
    {id:'marrakech-lantern-stack-compact-v2',reuseMask:'marrakech-lantern-stall-carpet-stack-peek',pose:'front-peek',eye:{x:652,y:579},face:23,context:{left:450,top:390,width:530,height:610},person:rect(490,310,80,106),action:'Compact upper body behind the existing carpet stack inside the lantern shop, shoulders narrow, elbows inward and hands together low at chest. Look three-quarter RIGHT at a hanging lamp, with part of the face clearly visible. No waving, lamp, carpet or scenery generated.',light:light('Visible hanging lamps above and upper-left','Warm amber lamp key in dark shop ambient','Low canopy ambient, skin remains far dimmer than lamp cores','Faint blue-glass reflection on the unlit side only'),basis:'Compact no-wave pose replaces the broad raised arm in the narrow pocket. Eye24 nativepixels lower and face23 from25; foregroundcarpetstack unchanged.'},
    {id:'marrakech-spice-compact-v2',reuseMask:'marrakech-front-orange-spice-basket-peek',pose:'front-peek',eye:{x:1395,y:853},face:24,context:{left:1190,top:690,width:580,height:600},person:rect(966,560,100,119),action:'Compact upper body behind the orange spice basket, head angled subtly LEFT toward the merchant. Both small hands together near the chest, elbows narrow and below the face. Do not hold a cup or touch the spice; existing merchant hands remain foreground. No basket, spice or cups generated.',light:light('Diffuse upper-left shop daylight','Warm subdued amber and orange reflected light','Medium shaded-stall midtones matching local faces','Restrained spice/brass bounce, no orange halo or luminous clothes'),basis:'Same settled spice eye anchor and actual foreground. Face reduced from27 to24 nativepixels within child scale, using compact hands to avoid protected merchant hands.'},
    {id:'marrakech-pottery-centre-parapet-v1',reuseMask:'marrakech-pottery-parapet-peek',pose:'seated',eye:{x:2325,y:1380},face:35,context:{left:2080,top:1190,width:690,height:650},person:rect(1460,660,77,151),action:'Relaxed seated upper body behind the existing pottery parapet. Torso turned gently LEFT, eyes glance toward the nearby tea gathering, at least three-quarter face visible. One forearm inward near the lap, shoulders low. Do not paint a seat, pots, tea glass, wall or scenery.',light:light('Soft overhead market daylight screened by the pottery-stall sidewall','Warm muted ochre fill over darker neutral shadow','Medium-low shaded pottery pocket','Soft warm terracotta reflection, weaker than the highlights on pots'),basis:'Source-blind 100 native-pixel shift RIGHT within the same broad pre-existing pottery wall. Addresses original left slack of 3–5 pixels; neither old source sheet nor original foreground pixels are changed.'},
  ],
  tokyo:[
    {id:'tokyo-open-near-dark-crossing-v1',pose:'standing',eye:pt(841,999),ground:1135*1.6,height:152*1.6,face:21*1.6,person:rect(950,930,75,185),action:'Stand on the dark near end of the crossing, both feet planted close together. Look three-quarter RIGHT toward the child in the red cardigan, hands loosely together at waist. Natural small child, no rigid front-facing portrait, props or pavement.',light:light('Diffuse night sky and distant shop/sign spill','Cool blue-violet ambient with very restrained amber side light','Dark crossing exposure like the nearby original red-cardigan child','Weak violet asphalt reflections; no strong rim or front portrait fill'),basis:'Clear dark asphalt immediately left of the red-cardigan child; width and height compared to that same-depth original child. Whole shoes sit in existing dark pavement, not on a bright lamp reflection.'},
    {id:'tokyo-open-mid-crossing-v1',pose:'standing',eye:pt(832,650),ground:760*1.6,height:120*1.6,face:17*1.6,person:rect(950,566,53,113),action:'Stand naturally in the dark crossing gap, both soles visible and flat. Turn three-quarter LEFT toward the shop, one arm relaxed and the other bent lightly across the waist. Keep the face partly visible with a curious expression, no waving or objects.',light:light('Cool open-street night fill with distant upper-left amber shop light','Predominantly blue-violet, muted warm highlights on shop-facing cheek','Medium-low night street exposure below lit shop faces','Very weak magenta sign reflections, no neon skin or glowing hair'),basis:'Same-depth small child in the patterned red outfit at display x980 provides child scale. Place on dark asphalt band rather than the pale crossing stripe.'},
    {id:'tokyo-lit-counter-compact-v2',reuseMask:'tokyo-original-shop-counter-seated',pose:'front-peek',eye:{x:2930,y:1468},face:27,context:{left:2730,top:1310,width:342,height:480},person:rect(1691,807,96,115),action:'Compact upper torso inside the existing lantern display shop. Turn three-quarter LEFT looking toward the illuminated toys, both arms relaxed and inward at waist; no raised hand. Face and hair share the lantern light of the original boy beside her. Existing counter hides lower body. No lantern, toys or counter generated.',light:light('Visible paper lantern above-right','Warm amber lantern key over cool night ambient','Localized warm shop exposure but never brighter than paper lanterns','Weaker warm tray bounce from below-left; faint cool unlit edge'),basis:'Same actual counter with compact non-wave pose; eye23 nativepixels lower and face27 rather than29 to keep the source inside broad countertop coverage.'},
  ],
};

// The whole-body layer path avoids silhouette-dependent artificial bottom cuts.
// Sources remain complete standing children; the existing original-pixel mask
// may hide their legs/torso in the final board. These support planes are authored
// behind the real object, not inferred from a particular generated child's box.
const layerContracts:Record<string,{height:number;ground:number;action:string;support:string}>={
  'amazon-root-pocket-compact-v2':{height:230,ground:1502,action:'Draw a COMPLETE standing child from crown to both shoes, torso leaning slightly RIGHT and compact arms near chest. Three-quarter face watches the river. The figure stands on the sheltered root-bank ground behind the thick roots, which will be composited later. No roots, water, scenery or shadow in the source.',support:'Hidden sheltered root-bank support; original roots are the foreground layer, not an artificial lower cut.'},
  'amazon-far-bank-compact-v2':{height:140,ground:716,action:'Draw a COMPLETE small standing child, both shoes visible in the source, knees gently relaxed, compact hands at waist. Face turns three-quarter LEFT watching a canoe. The child is behind the original far-bank rock, at the same depth as original bank children. No rock, canoe, water or props.',support:'Upper river-bank shelf behind the existing bank rock; its original pixels hide the legs.'},
  'giza-upright-block-compact-v2':{height:230,ground:1213,action:'Draw a COMPLETE standing child from crown to shoes, arms close and one hand resting naturally near waist. Three-quarter face looks RIGHT toward nearby children. The support is the raised stone terrace behind the large carved block; block pixels will be added later. No stone, tools, terrace or props.',support:'Raised terrace behind the large block, aligned with original children on that upper level rather than the lower foreground workers.'},
  'giza-textile-counter-compact-v2':{height:270,ground:1593,action:'Draw a COMPLETE standing child, both shoes visible in the source, body turned slightly RIGHT toward the vendor with a small close-to-body conversational hand gesture. Keep childlike proportions. The child stands in the shaded stall behind the textile counter; the original textiles will occlude the lower body later. No textiles, seat or objects.',support:'Stall floor behind the folded counter, in existing fabric-canopy shade.'},
  'greatwall-food-parapet-compact-v2':{height:180,ground:1854,action:'Draw a COMPLETE standing child with both shoes visible in the source, relaxed shoulders, one hand lightly touching the other wrist. Turn three-quarter LEFT watching the food-sharing children. Stand on the shaded landing behind the low food parapet; original stone pixels will occlude the lower body later. No food, mug, wall or props.',support:'Higher landing immediately behind the food parapet; not the lower public step in front.'},
  'marrakech-lantern-stack-compact-v2':{height:210,ground:768,action:'Draw a COMPLETE small standing child from crown to both shoes, arms low and compact, three-quarter face looking RIGHT at the lamps. Stand on the shop platform behind the carpet stack in dark lantern light. Existing carpet pixels will hide the lower body later. No waving, lamps, carpet or platform generated.',support:'Narrow raised lantern-stall platform behind stored carpets; existing carpet foreground may hide the shoes.'},
  'marrakech-spice-compact-v2':{height:260,ground:1087,action:'Draw a COMPLETE standing child, both shoes visible, compact arms with hands loosely together at waist. Face turned gently LEFT toward the merchant. Stand on the shaded stall floor behind the spice basket. Existing spice and merchant foreground pixels will be composited later. No basket, cup, spice, tools or contact shadow in source.',support:'Market floor behind the spice basket at the neighboring merchant depth, not on the basket or a tabletop.'},
  'tokyo-lit-counter-compact-v2':{height:270,ground:1710,action:'Draw a COMPLETE standing child from crown to both shoes, body and three-quarter face turned LEFT looking at illuminated toys, both arms relaxed inward at waist. Inside the lantern shop behind its display counter. Existing counter pixels will hide the lower body later. Face, hair and hands share amber lamp key with the nearby boy. No lamps, toys or counter generated.',support:'Shop floor behind the display counter in the same lantern-lit pocket; complete source is masked only with existing board foreground.'},
};
for(const candidates of Object.values(config))for(const c of candidates){const layer=c.id?layerContracts[c.id]:undefined;if(layer){c.pose='standing';c.height=layer.height;c.ground=layer.ground;c.action=layer.action;c.basis=`${c.basis} Whole-body original-foreground layer: ${layer.support} Candidate support/scale require final composite review, not certified by this authoring.`;}}
// Final original-board inspection: keep the face in the root GAP (not on bark),
// and replace the ambiguous far-bank/water support with actual shaded dry land.
config.amazon![0]!.eye={x:626,y:1230};config.amazon![0]!.ground=1437;
config.amazon![0]!.basis='Original-board visual check moved the head into the open gap just above the thick root. Root foreground unchanged; sheltered bank support behind roots at native y1437. Whole-body source, no artificial bottom cut. Pending composite contact/lighting review.';
config.amazon![1]={id:'amazon-open-shaded-fruit-bank-v4',pose:'standing',eye:pt(1603,601),ground:715*1.6,height:126*1.6,face:18*1.6,person:rect(1516,552,77,187),action:'Draw a COMPLETE standing child from crown to both shoes, on the shaded dry riverbank beside the fruit basket. Turn three-quarter LEFT watching the canoe, one hand loosely resting over the other at waist. Compact natural child, not a portrait pose. No basket, fruit, water, ground or shadow generated.',light:light('Filtered broad canopy daylight near the fruit porch','Muted warm-green canopy shade, neutral skin midtones','Shade matching the nearby blue-shirt child; no illuminated hair cap','Weak olive ambient and restrained warm basket reflection'),basis:'Replaces ambiguous far-bank/water support. Actual dry bank in the existing basket/canopy shade between the original blue-shirt child and fruit basket; scale126displaypixels based on that same-depth original child.'};
config.marrakech![0]!.eye={x:652,y:565};config.marrakech![0]!.ground=754;

async function alphaForeground(boardPng:Buffer, polygon:Point[]) {
  const {data,info}=await sharp(boardPng).ensureAlpha().raw().toBuffer({resolveWithObject:true}); const dest=Buffer.alloc(data.length);
  const inside=(x:number,y:number)=>{let hit=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i]!,b=polygon[j]!;if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)hit=!hit;}return hit;};
  for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(inside(x+.5,y+.5)){const i=(y*info.width+x)*4;data.copy(dest,i,i,i+4);dest[i+3]=255;}
  return sharp(dest,{raw:{width:info.width,height:info.height,channels:4}}).png().toBuffer();
}
async function audit(board:any, slots:any[], dir:string) {
  const originalSpec=read(`${OLD}/world-${board.boardId}-spec.json`);const input=(await loadBoardConditioningInputs(originalSpec))[0]!;
  const sources:any[]=[];
  for(const run of RUNS[board.boardId]??[]){const result=read(`${OLD}/${run}/result.json`);for(let i=0;i<3;i++){const seed=result.extracted?.sprites?.find((s:any)=>s.slotId===input.slots[i]!.slot.id);const file=`${OLD}/${run}/sprite-${i+1}.png`;if(seed&&existsSync(file))sources.push({run,index:i+1,seed,png:readFileSync(file)});}}
  const rows:any[]=[];
  for(const catalogSlot of slots){const slot=read(catalogSlot.placement.priorResultMetadata.path).slot;if(slot.mode==='open'){rows.push({slotId:catalogSlot.slotId,mode:'open',status:'unrendered-source-blind-candidate',sixSilhouetteMargin:'not-applicable; whole-body support, scale and visual contact must be tested'});continue;}
    const fg=readFileSync(catalogSlot.placement.foreground.path);const foreground={png:fg,sha256:sha256Bytes(fg)};const mask=await sharp(fg).ensureAlpha().raw().toBuffer({resolveWithObject:true});const checks:any[]=[];
    for(const s of sources){const seed=s.seed,source={png:s.png,sha256:seed.sha256,eye:seed.eye,chin:seed.chin,protectedFacePolygon:seed.protectedFacePolygon,measurement:seed.measurement};const d=Math.hypot(seed.chin.x-seed.eye.x,seed.chin.y-seed.eye.y);let cut:number|null=null;
      let robust:Awaited<ReturnType<typeof chooseRobustPeekCut>>=null;
      try{if(process.argv.includes('--robust')){robust=await chooseRobustPeekCut({board:input.board,foreground,slot,source},{minCutY:Math.ceil(seed.chin.y+d)});cut=robust?.lowerCutY??null;}else cut=await findSimplePeekCut({board:input.board,foreground,slot,source},{minCutY:Math.ceil(seed.chin.y+d)});}catch{}
      if(cut===null){checks.push({run:s.run,index:s.index,ok:false,reason:'no-occluded-cut',slack:0});continue;}
      const composite=await composeSimplePeek({board:input.board,foreground,slot,source:{...source,lowerCutY:cut}});const raw=await sharp(s.png).ensureAlpha().raw().toBuffer({resolveWithObject:true});const scale=slot.faceHeightPx/d,tx=slot.eye.x-seed.eye.x*scale,ty=slot.eye.y-seed.eye.y*scale;let lo=Infinity,hi=-Infinity;
      for(let x=0;x<raw.info.width;x++)if(raw.data[((cut-1)*raw.info.width+x)*4+3]!>0){lo=Math.min(lo,tx+x*scale);hi=Math.max(hi,tx+(x+1)*scale);}
      const by=Math.round(ty+(cut-1)*scale);let L=0,R=0;const solid=(x:number)=>x>=0&&x<mask.info.width&&by>=0&&by<mask.info.height&&mask.data[(by*mask.info.width+x)*4+3]===255;
      while(solid(Math.floor(lo)-L-1))L++;while(solid(Math.ceil(hi)+R+1))R++;
      checks.push({run:s.run,index:s.index,ok:composite.ok,cut,left:robust?.margin.leftMarginPx??L,right:robust?.margin.rightMarginPx??R,slack:robust?.margin.worstSideMarginPx??Math.min(L,R),...(robust?{exactNativeMargin:robust.margin}:{}),failedChecks:Object.entries(composite.checks).filter(([,v])=>!v).map(([k])=>k)});
    }
    const minSlack=Math.min(...checks.map(c=>c.slack));rows.push({slotId:catalogSlot.slotId,mode:'clipped',bar:slot.faceHeightPx,sourceCount:sources.length,minSlack,pass:sources.length===6&&checks.every(c=>c.ok)&&minSlack>=slot.faceHeightPx,checks});
  }
  out(`${dir}/${process.argv.includes('--robust')?'robust-six-silhouette-audit':'six-silhouette-audit'}.json`,{paidCalls:0,visualApproval:false,rows});return rows;
}
async function main(){const boardId=process.argv[2];if(!boardId||!config[boardId])throw new Error('Choose configured board: '+Object.keys(config).join(','));const revision=process.argv.find(a=>a.startsWith('--revision='))?.slice(11);if(revision&&!/^[a-z0-9-]+$/.test(revision))throw new Error('Safe revision required');const dir=`${ROOT}/${boardId}${revision?'/'+revision:''}`;mkdirSync(dir,{recursive:true});const catalog=read(CATALOG),board=catalog.boards.find((b:any)=>b.boardId===boardId);const originalSlots=structuredClone(board.slots);const original=readFileSync(board.staticArt.path);const clear=await sharp({create:{width:3072,height:2048,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).png().toBuffer();writeImmutableBytes(`${dir}/clear.png`,clear);const bound=(p:string,bytes:Buffer)=>({path:p,sha256:sha256Bytes(bytes)});const markers:string[]=[];
  board.slots=await Promise.all(config[boardId]!.map(async(c,i)=>{if(c.keep){const prior=structuredClone(originalSlots.find((s:any)=>s.slotId===c.keep));const meta=read(prior.placement.priorResultMetadata.path);meta.slot.cutSelection='two-hidden-rows-one-face-side-margin/v1';meta.semanticStatus='pending';const file=`${dir}/${prior.slotId}-robust.json`,bytes=Buffer.from(JSON.stringify(meta,null,2));writeImmutableBytes(file,bytes);prior.placement.contract=bound(file,bytes);prior.placement.priorResultMetadata=bound(file,bytes);return prior;}const prior=structuredClone(originalSlots.find((s:any)=>s.slotId===c.reuseMask)??originalSlots[i]);const oldSlot=read(prior.placement.priorResultMetadata.path).slot;const id=c.id!;const isOpen=c.pose==='standing';const eye=c.eye!;const window=c.context??{left:eye.x-100,top:Math.round(c.ground!-c.height!-35),width:200,height:Math.round(c.height!+55)};
    const fg=c.reuseMask?readFileSync(prior.placement.foreground.path):c.polygon?await alphaForeground(original,c.polygon):clear;const fgPath=c.reuseMask?prior.placement.foreground.path:`${dir}/${id}-foreground.png`;if(!c.reuseMask)writeImmutableBytes(fgPath,fg);
    const slot={id,pose:c.pose,eye,faceHeightPx:c.face,window,...(isOpen?{mode:'open',supportPointPx:{x:eye.x,y:c.ground},standingHeightPx:c.height}:{cutSelection:'two-hidden-rows-one-face-side-margin/v1'}),forbiddenRects:[...(c.reuseMask?oldSlot.forbiddenRects??[]:[]),...(c.forbidden??[c.person!]).filter(Boolean).map((r,j)=>({id:`original-person-protected-${j}`,...r}))],...(c.reuseMask&&oldSlot.forbiddenPolygons?{forbiddenPolygons:oldSlot.forbiddenPolygons}:{})};
    const meta={slot,boardSha256:board.staticArt.sha256,foregroundSha256:sha256Bytes(fg),semanticStatus:'pending',authoring:{kind:'source-blind-candidate',basis:c.basis,originalPeopleMeasurement:{rect:c.person,method:'manual from unpersonalized native board; not a model-validated scale measurement'},paidCalls:0,visualApproval:false}};const file=`${dir}/${id}.json`;const bytes=Buffer.from(JSON.stringify(meta,null,2));writeImmutableBytes(file,bytes);
    prior.slotId=id;prior.pose={family:c.pose,instruction:c.action,lowerBodyPolicy:isOpen?'Whole body, both shoes visible; never generate scenery or a shadow detached from the figure.':'Only already-painted foreground pixels may hide the lower body. No invented props.'};prior.lighting=c.light;prior.placement={...prior.placement,contract:bound(file,bytes),priorResultMetadata:bound(file,bytes),foreground:bound(fgPath,fg),eyeAnchorPx:eye,eyeToChinPx:c.face,contextRectPx:window,anchorMode:isOpen?'observed-soles':'fixed-eyeMidpoint',modifiedByThisCatalog:true};prior.references={localStaticCrop:null,localStaticCropRectPx:window,originalPersonExample:null,originalPersonExampleRectPx:c.person};return prior;}));
  for(const [i,s]of board.slots.entries()){const slot=read(s.placement.priorResultMetadata.path).slot;const w=slot.window;markers.push(`<rect x="${w.left}" y="${w.top}" width="${w.width}" height="${w.height}" fill="none" stroke="#f8df30" stroke-width="4"/><circle cx="${slot.eye.x}" cy="${slot.eye.y}" r="7" fill="#f8df30"/><text x="${w.left+8}" y="${w.top+28}" font-size="26" fill="#f8df30">${i+1} ${slot.mode==='open'?'OPEN':'CLIPPED'}</text>`);if(slot.supportPointPx)markers.push(`<circle cx="${slot.supportPointPx.x}" cy="${slot.supportPointPx.y}" r="9" fill="#36e6e6"/>`);}
  catalog.boards=[board];out(`${dir}/catalog.json`,catalog);const spec=read(`${OLD}/world-${boardId}-spec.json`);spec.catalogPath=`${dir}/catalog.json`;spec.sourcePresentation='local-composite/v5';delete spec.slotDirectionOverrides;out(`${dir}/spec.json`,spec);writeImmutableBytes(`${dir}/candidates.png`,await sharp(original).composite([{input:Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="3072" height="2048">${markers.join('')}</svg>`)}]).png().toBuffer());console.log(JSON.stringify({boardId,dir,slots:board.slots.map((s:any)=>s.slotId),paidCalls:0,visualApproval:false}));
  if(process.argv.includes('--validate')){const [input]=await loadBoardConditioningInputs(spec);await prepareBoardConditionedSource(input!,{quality:'medium',reserveMicroUsd:200000,providerNamespace:'openai:find-me-existing',timeoutMs:240000,rateCard:{id:'authoring-preflight-only',textInput:5,imageInput:8,imageOutput:30}});out(`${dir}/preflight.json`,{paidCalls:0,quality:'medium',sourcePresentation:spec.sourcePresentation,valid:true,visualApproval:false});console.log('FREE INPUT AND PROMPT PREFLIGHT PASS');}
  if(process.argv.includes('--audit'))console.log(JSON.stringify(await audit(board,board.slots,dir),null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
