/** Freeze art-only density edits; no provider calls, child work, or game mutations. */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';

const activities: Record<string, string> = {
  paris: `Occupy the open foreground paving between the flower planters, metro railing and portrait area, the outer left cafe lane and right bookseller edge. Add small groups: three children making a chalk hopscotch pattern; a parent helping a child tie a shoe with a sibling watching; two flower-delivery helpers and a customer; a baker offering bread to a family of three; four cafe spectators gently clapping to the existing musician; two children swapping postcards with their grandfather; a dog walker offering water while a child watches; three friends sharing crepes; a child showing a sketch to two relatives; two shoppers inspecting a basket; three friends consulting a folded map; two people fixing a bicycle chain with a child holding the pump. Mix standing, sitting, crouching and walking figures. Do not block the existing fountain, portrait faces or six collectibles.`,
  marrakech: `Fill the open lower courtyard paving, both outer stall lanes and the spaces beside the existing tea and pottery groups. Add small groups: four people learning to weave a basket; a cobbler showing a repair to a parent and child; three market helpers portioning dates; four children trying a wooden shape puzzle; three adults rolling an ordinary plain rug; a woman kneading dough while two children watch; three shoppers comparing woven baskets; a grandfather explaining a small balance scale to two children; three friends tasting olives; two helpers carrying a small crate together; a tailor measuring a sleeve while a relative watches; a family of four following a storyteller's hand gesture. Add natural working gestures and real little interactions. No additional eye amulet, striped slipper, crescent cup, tasseled key, violet gecko or silver camel motif.`,
  tokyo: `Add activity to the lower paving between existing seated groups, the left plant-shop lane, the right bicycle/fruit-stall edge and small openings around the middle courtyard. Add groups: three children playing a pebble game; a parent teaching two children to tie a parcel; three friends tasting ordinary rice snacks; a lantern maker with two young helpers; a florist showing a sprig to two customers; a grandparent reading with two children; three children sharing crayons and sketching roof tiles; a family of four observing the existing drummers; a vendor weighing fruit for a parent and child; two helpers carrying a small empty wooden tray; three neighbors chatting while one repairs a bicycle; three friends resting on low stools. Fill interstices without removing existing people or moving the craft table. No extra robots, decorated red fans, fish windsocks, origami frogs, lucky cats or gold cranes.`,
  greatwall: `Use the broad foreground stone terrace between and beside the existing planters, the left outer tea-stall edge, the right foreground lane and accessible openings on the upper inhabited terrace. Do NOT add crowds onto the distant mountain wall. Add groups: four children examining leaf rubbings on loose paper with one adult; three travelers sharing binoculars; three family members eating a modest picnic; an adult helping a child wind ordinary kite string while a sibling watches; two helpers carrying a crate; a guide explaining stonework to three listeners; three children trying a small wooden tangram; a parent adjusting a child's hat while another child waits; three visitors sketching on notebooks; two friends refilling plain cups; three walkers resting on a low bench; two grandparents listening to a child. Preserve the visible travel box with the red dragon collectible and all existing targets. Do not let new bodies hide the principal faces.`,
  sydney: `Populate the open foreground paving between the flower planters and craft tables, the outer left market lane, the right promenade and openings around the ferry queue. Keep the water strip and landmarks untouched. Add groups: three children drawing a chalk harbor map; a parent putting sunscreen on a child with a sibling waiting; three market helpers sorting ordinary fruit; four relatives sharing a small picnic; a dog walker talking to a parent and child; three listeners clapping along to the musicians; a parent adjusting a bike helmet for a child with a sibling watching; three visitors comparing sketches; two helpers carrying a small crate; a grandfather reading to two children; a family of three receiving a paper bag of snacks; three friends observing an ordinary leaf through a magnifying glass. Do not create extra target-design goggles, bucket, life ring, boomerang, paper airplane or pearl shell. Keep the original six targets discoverable.`,
  antarctica: `This board needs the strongest foreground fill: populate the broad open lower snow, the gaps between equipment islands, and the snow lanes next to both huts. Put at least 22 of the additional people in the lower half. Add groups: four people sorting ice samples on a low tray; three people hauling a small supply sled together; an adult teaching two children a rope knot; three helpers bundling plain rolled blankets; a scientist demonstrating a small wind instrument to three children; three children comparing snow footprints with a guide; a parent adjusting a child's boot while a sibling waits; three friends comparing nature sketches; three people packing ordinary lunch bags; two staff repairing a sledge runner; a guide sharing binoculars with two children; three helpers arranging unmarked sample jars on a crate. Insulated clothing, open faces, varied kneeling/seated/standing poses, warm expressive faces and cool snow shadows. People stay on the near station ground, not in the sea, on roofs or tiny on distant cliffs. Respect space around wildlife. Do not duplicate target cup, mitten, goggles, compass, orange toy penguin or snowflake pendant.`,
};

async function main() {
  const directory = 'output/imagegen/adventure-density-20260914-v3';
  const planFile = `${directory}/plan.json`;
  if (existsSync(planFile)) throw Error('Frozen density plan already exists. Use a new version.');
  const previous = JSON.parse(readFileSync('output/imagegen/adventure-expansion-20260914-v1/plan.json', 'utf8'));
  const sources = previous.boards as { id: string; items: string }[];
  if (sources.length !== 6 || sources.some(board => !activities[board.id])) throw Error('Unexpected board scope');
  mkdirSync(directory, { recursive: true });
  const boards = [];
  for (const board of sources) {
    const source = `public/scenes/adventure-${board.id}-zoomout-v2/base.webp`;
    const input = `${directory}/${board.id}-source.png`;
    const promptFile = `${directory}/${board.id}.prompt.txt`;
    if (existsSync(input) || existsSync(promptFile)) throw Error(`Inputs already exist: ${board.id}`);
    const metadata = await sharp(source).metadata();
    if (metadata.width !== 3840 || metadata.height !== 2160) throw Error(`Unexpected source size: ${board.id}`);
    await sharp(source).png().toFile(input);
    const prompt = `Use case: precise-object-edit.
Asset type: 16:9 illustrated seek-and-find game board for ages 4-10.
Input image: the supplied ${board.id} board is the EDIT TARGET and sole authoritative visual/style reference.

CHANGE ONLY THE POPULATION AND SMALL HUMAN ACTIVITIES. The parent likes this zoomed-out camera but finds the opened ground too sparsely populated. Add approximately 35-45 ADDITIONAL, individually drawn people in 10-14 coherent little scenes. The result must visibly have many more people, not simply more props or plants. Retain ALL the existing people and their stories; supplement, do not replace them with a different crowd. Place new figures into the open ground and interstices, including peripheral and foreground gaps, so the whole playable surface feels richly inhabited. Short breathing paths remain, but no big blank forecourt. Group members must interact with each other and a real activity, rather than stare out at the viewer or stand in neat rows.

BOARD-SPECIFIC ADDITIONS: ${activities[board.id]}

LOCK FRAME AND SCALE: exactly the same full frame, elevated viewing angle and shallow compressed perspective as the input. No zoom in, no further zoom out, no crop, no outpainting, no new horizon, no long corridor or faraway vanishing point. All existing buildings, landmarks, stalls and principal objects stay in their original positions at their original size. New people match the already-small neighboring people at the same plane. Do not enlarge foreground heads or create close-up front-row figures. Do not make a tiny distant population to meet the count. Activity spreads across height and width rather than receding in depth. Keep every original face recognizable and untouched wherever possible. Place additions beside rather than on top of existing people and collectible objects.

EXACT ART STYLE: match this input's specific illustrated faces, freely drawn brown contour lines with varying weight, matte painterly color, tactile selective brush strokes, fabric folds, expressive hands and crisp shaped transitions between light and shadow. Not photorealism. Do not polish, airbrush, smear, blur, add CGI gloss, switch to flat vector/cel art, or apply a uniform grain filter. Maintain the original local palette, sunlight direction, warmth and cool shadow colors. Added faces need clearly separated eyes with pupils, eyebrows, noses and mouths at native 4K, coherent limbs, plausible hands, varied expressions, hair, ages and clothing. New paint must look from the very same illustrator as the unchanged source.

PROTECT EXISTING COLLECTIBLES: keep all six target designs exactly once and in their current image locations. Preserve their existing scale, visibility and partial occlusions. Do not duplicate them on added props/clothes; do not emphasize or halo them. This older list defines IDENTITIES ONLY; the supplied picture overrides its location descriptions: ${board.items}

OUTPUT: one full-bleed native 3840x2160 image, no UI, labels, captions, borders, arrows, marks or personalized child insertions. Significant visible population increase at the SAME camera and scale; everything else remains the same.`;
    writeFileSync(promptFile, prompt);
    boards.push({ id: board.id, source, sourceSha256: createHash('sha256').update(readFileSync(source)).digest('hex'), input, promptFile, output: `${directory}/${board.id}-4k.png` });
  }
  writeFileSync(planFile, JSON.stringify({ version: 'adventure-density-20260914-v3', model: 'gpt-image-2', size: '3840x2160', quality: 'high', requestedCalls: 6, targetAdditionalPeoplePerBoard: [35, 45], childPlacementAllowed: false, hideAuthoringAllowed: false, boards }, null, 2));
  console.log(`Prepared ${boards.length} art-only density edits, no child rendering.`);
}
main().catch(error => { console.error(error); process.exitCode = 1; });
