import {readFileSync,writeFileSync,existsSync} from 'node:fs';
const dir='output/imagegen/adventure-expansion-20260914-v1';
const style=`Match the Giza reference's actual illustration language: warmly lit, lively colored hand-painted children's adventure illustration. Rounded appealing faces, clear individual eyes, confident irregular dark brown contours and broad clean painted color shapes with a few deliberately sculpted shadow planes. Selective little brush accents, NOT a mottled surface covering everything. Bright readable ochre/cream lit surfaces and restrained cool shadows. NO grey-brown wash, NO antique engraving, NO crosshatching all over skin, NO watercolor blotching, NO uniform paper noise. Keep hand-drawn character, do not make plastic CGI, vector cartoons or airbrushed realism. Faces should have the same gentle storybook stylization as the actual faces in Giza. Atmospheric warm daylight but local colors remain distinct. The finish must look like another page from the Giza illustrator, not a different book.`;
for(const slug of ['paris','marrakech','tokyo','greatwall','sydney','antarctica']){
 const destination=`${dir}/${slug}-style-v2.prompt.txt`;if(existsSync(destination))throw Error('Frozen follow-up exists');
 const original=readFileSync(`${dir}/${slug}.prompt.txt`,'utf8');
 const isCorrection=!['sydney','antarctica'].includes(slug);
 let prompt=isCorrection?`Use case: style-transfer. Image 1 is the authoritative GIZA STYLE reference only. Image 2 is the ${slug} EDIT TARGET: retain its exact scene, broad spatial layout, shallow perspective, people activities and six collectible identities and locations. Repaint the entire second image into the FIRST image's drawing language, not the reverse. Output only the second scene, 3840x2160 full bleed. ${style}\nKeep every target in the same region, naturally mixed into the scene. The single rare brass key should be a small ordinary pocket key, not a giant emblem: reduce its linear size by half and tuck 25 percent under the adjacent cloth; retain its colored ribbon/tassel. Epic target should remain recognizable but 35 percent behind a natural overlapping object; no display pedestal or halo. Do not introduce Egyptian scenery, UI, text labels or duplicated collectibles. Preserve all readable faces and correct hands.\n${original.slice(original.indexOf('EXACT SIX COLLECTIBLES:'))}`:`${original}\nAUTHORITATIVE STYLE OVERRIDE: ${style}`;
 if(slug==='tokyo'||slug==='greatwall')prompt=prompt.replace('The single rare brass key should be a small ordinary pocket key, not a giant emblem: reduce its linear size by half and tuck 25 percent under the adjacent cloth; retain its colored ribbon/tassel. ','');
 writeFileSync(destination,prompt);
}
