/**
 * The SQLite schema as plain SQL, checked in, for the test suite.
 *
 *   npm run db:sql
 *
 * The integration tests used to run `prisma db push` against a temp database,
 * which needs Prisma's schema engine at test time. On one reviewer's machine
 * that engine failed to start — the dev server was holding the binaries — and
 * the whole pipeline suite was skipped, 16 tests reported as "passed". Now the
 * tests execute this file statement by statement through the client they
 * already have. The first line carries a hash of schema.prisma, so a stale
 * file fails the suite with a message instead of silently testing the past.
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const schema = readFileSync("prisma/schema.prisma", "utf8").replace(/\r\n/g, "\n");
const hash = createHash("sha256").update(schema).digest("hex");
const sql = execFileSync("npx", ["prisma", "migrate", "diff", "--from-empty", "--to-schema-datamodel", "prisma/schema.prisma", "--script"], {
  encoding: "utf8",
  shell: process.platform === "win32",
  stdio: ["ignore", "pipe", "inherit"],
});
writeFileSync("prisma/test-schema.sql", `-- schema-sha256: ${hash}\n-- Generated by scripts/prisma-sql.mjs from prisma/schema.prisma. Do not edit; run: npm run db:sql\n${sql.replace(/\r\n/g, "\n")}`);
console.log(`prisma/test-schema.sql written for schema ${hash.slice(0, 12)}`);
