/** V12 only. Identity geometry and scene rendering are independent obligations. */
export const INTEGRATION_CHECKS = ["styleMatch", "lightingMatch", "neighborsIntact"] as const;
export const INTEGRATION_REPAIR_DIRECTIONS = {
  styleMatch: "Retain the child's unique facial geometry, hairline and hair pattern. Draw their SURFACE with the original neighbours' visible ink-like contours and a few clearly separated matte light/shadow shapes. Eyes, nose and lips use economical illustrated marks; curls form broad dark locks with sparse painted accents, not individual strands. Match the original faces at the same scale. Remove photographic gradients, tiny hairs and portrait-detail density; do not blur the face, apply a texture filter or copy a neighbour's features.",
  lightingMatch: "Match the original neighbours' local exposure, shadow direction, shadow depth, highlight strength and edge contrast. Remove portrait fill light, bright rim, skin glow and spotlight. Preserve actual skin/hair colour and readable identity; do not indiscriminately darken the child.",
  neighborsIntact: "Restore EVERY original neighbouring head, face, neck, body, hand and clothing silhouette at its original coordinates. Only the single person intentionally replaced by the child may change, and that replacement must be complete. No duplicate or stacked faces, half-erased people, mismatched head/body, foreign limbs or blend through a foreground person. Keep all foreground occluders intact. Move the child or edit boundary within the authored location if needed.",
} as const;

export const INTEGRATION_REVIEW_DIRECTION = [
  "INTEGRATION REVIEW: all identity/body checks AND styleMatch, lightingMatch, neighborsIntact, childPresent, childOnlyOnce, childComplete and pictureWhole require explicit pass. A recognizable face does not excuse a photographic finish, brighter lighting or a damaged neighbour.",
  "FIRST compare BEFORE and AFTER around the entire generated child and every edge of the returned patch, including people BELOW the child. Identify each neighbouring head and follow its neck, torso and limbs. neighborsIntact fails for a new head over an old face, stacked/doubled faces, a forehead/scalp cut by a planter or patch, a painted head on another person's body, an erased body part, or an anatomically inconsistent foreground overlap. Natural occlusion is valid when foreground silhouettes remain coherent. Complete intentional replacement of one person is allowed; damage to another person is not. The target may shift or change pose within the authored location: reducing its overlap with an intact foreground person is NOT damage to that person. Do not report harmless background colour drift or demand identical pixels.",
  "SECOND compare the target FACE AND HAIR with two original neighbouring faces at comparable visible size. styleMatch fails when the child has smoother photographic skin, more individual hairs, glassier eyes, softer portrait gradients or finer detail than those people, even if their outfit looks painted. Identity likeness must be retained through feature geometry, not photographic texture. A coloured photograph is not matching illustration.",
  "A style pass means the same illustrated contour vocabulary, discrete matte painted shapes and edge treatment at actual player scale. A clearly outlined, flat-painted face is not photographic merely because it is recognizable, faces the viewer or has curly rather than straight hair. Distinguish natural hair pattern from rendering density. Judge visible surface handling, not generic assumptions about inserted targets; identify the actual photographic cue if failing.",
  "THIRD compare lighting at the same depth and light zone. lightingMatch fails for added portrait fill light, glowing face/hair, a bright rim or stronger contrast that singles the child out without a light source shared by nearby people. Different natural skin tones are not an exposure defect. Never require identical skin colour.",
  "Account for face orientation and the actual stall/window light: a forward-facing face naturally exposes different planes than a profile. Shared warm painted contour accents are not automatically a rim-light defect. Require a visibly unsupported exposure or highlight difference, not simply greater facial visibility.",
  "Return lightingMatch and neighborsIntact as pass|fail|unsure in EVERY verdict. Also return integrationEvidence as {style: string, lighting: string, neighbors: string}; each sentence must identify the actual compared people/location and observed rendering or anatomy. Generic 'coherent' or 'looks good' is insufficient. Missing evidence is not approval. For every fail give its own faults entry with its exact check name and visible location. If unsure, request another automatic diagnosis/repair; never waive a check for publication.",
].join("\n");
